name: Second build criu

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
    - uses: actions/checkout@v2

    - name: Run build criu
      run: |
        pwd
        pushd .
        cd $HOME
        git clone https://github.com/checkpoint-restore/criu.git
        cd criu
        pwd
        sudo -E make -C scripts/ci local
        echo "Done..."
      shell: bash
